### ISSUE TITLE
Revision of IPv6 support

### ISSUE THREAD

**Issue by Lirt** [Vnet-as/postfwd-anti-geoip-spam-plugin#12]
Check what needs to be changed to support IPv6

**Comment by Lirt** [comment]
We should probably use function `country_code_by_addr_v6` to get Country Code of IPv6 address.

**Comment by timelordx** [comment]
You might need to update your client IP check to validate IPv6. I'm not sure whether the following will work in Perl, but this is my regex for IPv6 `egrep` in BASH:

`^((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?$`

**Comment by Lirt** [comment]
Yes @timelordx that would be also needed.

Such a nice regex :D, this is crazy.

**Comment by croessner** [comment]
Hi, are there any chances to get IPv6 support implemented? I quickly disabled the client-address-check and resized the varchar from 16 to 40 for ip addresses, but it seems that is not enough at the moment. Unfortunately I am not a Perl developer.

**Comment by Lirt** [comment]
Hi @croessner,

I would like to add IPv6 support. Last time I was adding support for GeoIP2 DBs and I noticed that they support mixed databases (I hope that is true for all of their v2 databases). So maybe adding support for IPv6 only for GeoIP2 would be not that complicated. 

Will it suit your needs to have IPv6 support only for GeoIP2 DBs?

What I don't want to do very much is having multiple GeoIP files - one for IPv4 and one for IPv6. This will complicate the code and configuration file a lot. Anyway I think GeoIP1 is most likely not supported anymore, so I can leave the code, but focus only on GeoIPv2. Perl libraries are not helping in this case as well (they are not supported and hard to use).

**Comment by Lirt** [comment]
Hello @timelordx @croessner and everyone,

I created PR for IPv6 support https://github.com/Vnet-as/postfwd-anti-geoip-spam-plugin/pull/65.

All tests passed fine, I'm waiting for CI to return the same. The change was not as big as I thought it will be and the PR looks pretty clean.

So far I tested this feature only with GeoIP2 database and I'm thinking I will drop support for GeoIP1 with this release. Right now I cannot even find if GeoIP1 supports IPv6 and if yes there is question if there can be both IP versions in one DB file. It would be great to drop the support to simplify interface. Also automatic tests are only done on GeoIP2 DBs as test ones are available publicly.

There is also a breaking change because I needed to extend size of `ip_address` column in DB. More in PR description.

Please give me your insight into this and also feel free to do code review.

**Comment by francoisPE** [comment]
Hello,
I implemented that upgrade and thought everything good...
I am now not so sure. 
Looking in postfwd_logins table, I can't see any IPv6 address. 
How can I check it collect ipv6 if any ? 
I though connection from home with thunderbird would create such IPv6 address collected...

**Comment by Lirt** [comment]
Hi @francoisPE,

I think that the issue must be either in `postfix` or `postfwd` configuration. 

Postfix is sending `client_address` field - which contains IPv4 or IPv6 address ([in smtpd policy format](http://www.postfix.org/SMTPD_POLICY_README.html)) to `postfwd` which hands it out to the plugin. So from plugin point of view I only work with the `client_address` (either IPv4 or IPv6), but it needs to be passed from `postfix`. 

If you have logging enabled you should see every request that arrives to the plugin in the log file in this format:

```bash
tests-postfwd-geoip-antispam-1  | 2022-07-11 18:22:27 postfwd::anti-spam-plugin INFO[10]: Number of logins from IP 89.160.20.128 is 1
tests-postfwd-geoip-antispam-1  | 2022-07-11 18:22:28 postfwd::anti-spam-plugin INFO[10]: Number of unique countries logged in from user [valid-user@example.com]: 2
tests-postfwd-geoip-antispam-1  | 2022-07-11 18:22:28 postfwd::anti-spam-plugin INFO[10]: Number of unique IPs logged in from user [valid-user@example.com]: 6
tests-postfwd-geoip-antispam-1  | 2022-07-11 18:22:28 postfwd::anti-spam-plugin INFO[10]: Inserting valid-user@example.com, 2a02:d3c0::12, GB
tests-postfwd-geoip-antispam-1  | 2022-07-11 18:22:28 postfwd::anti-spam-plugin INFO[10]: Number of logins from IP 2a02:d3c0::12 is 1
tests-postfwd-geoip-antispam-1  | 2022-07-11 18:22:28 postfwd::anti-spam-plugin INFO[10]: Number of unique countries logged in from user [valid-user@example.com]: 2
tests-postfwd-geoip-antispam-1  | 2022-07-11 18:22:28 postfwd::anti-spam-plugin INFO[10]: Number of unique IPs logged in from user [valid-user@example.com]: 7
```

So from this log message it is very easy to see what was sent from `postfix` to `postfwd` and to plugin.

Can you please check if you have IPv6 addresses in the log? If not, you most likely need to check configuration of postfix.

**Comment by francoisPE** [comment]
My mistake, I forgot to run ./install.sh after git pull...
Now, it works and I see IPv6 in logs and MariadB
Thanks a lot for that great plugin
