### ISSUE TITLE
Upgrade GeoIP database to version 2

### ISSUE THREAD

**Issue by Lirt** [Vnet-as/postfwd-anti-geoip-spam-plugin#45]
GeoIP databases version 1 are obsolete and hard to download. Migrate code to GeoIP v2 Perl module and rewrite install script, documentation and Docker to use GeoIP databases v2.

Consider using `geoipupdate` in Docker.

**Comment by timelordx** [comment]
Until you migrate your code to GeoIP v2, you can still use your existing code with the following up-to-date GeoIP v1:

- [sherpya/geolite2legacy](https://github.com/sherpya/geolite2legacy)
- [GeoIP Legacy Databases (DAT)](https://www.miyuru.lk/geoiplegacy)

**Comment by Lirt** [comment]
Thank you, I might put them into documentation.
