### ISSUE TITLE
Move country and ip limit to separate configuration section

### ISSUE THREAD

**Issue by Lirt** [Vnet-as/postfwd-anti-geoip-spam-plugin#48]
Configuration options for country and ip limit should reside in `app` configuration section.

```conf
[app]
country_limit = 5
ip_limit = 20
```

**Comment by timelordx** [comment]
I, personally, would rather move it to the `[logging]` section. In this case, both `country_limit` and `ip_limit` are related to a logging behaviour, not the actual ratelimit (which would make it `[app]`).

**Comment by Lirt** [comment]
Closed in https://github.com/Vnet-as/postfwd-anti-geoip-spam-plugin/pull/62
