### ISSUE TITLE
warning: DBI connect

### ISSUE THREAD

**Issue by luis-git** [Vnet-as/postfwd-anti-geoip-spam-plugin#52]
Hello im supposing that this works with Maria Database as well, if not can i adjust it?
![Screenshot_20200530_002549](https://user-images.githubusercontent.com/9680925/83310580-d0866f80-a20c-11ea-8018-5873dcb46d90.png)

**Comment by luis-git** [comment]
Sorry it was my mistake i just forgot to "GRANT ALL ON finance.* TO user;" in Database and now its fine , i'm closing this issue.

**Comment by Lirt** [comment]
Hi @luis-git, glad you solved it :-).
