### ISSUE TITLE
Geo::IP object version 1.43 does not match bootstrap parameter 1.45

### ISSUE THREAD

**Issue by SuperSpital** [Vnet-as/postfwd-anti-geoip-spam-plugin#70]
Hi,
Just configured everything and I can't sent any mail (SMTP 451 error). I checked mail log and I got following error: "FATAL: Geo::IP object version 1.43 does not match bootstrap parameter 1.45 at /usr/lib/perl/5.18/DynaLoader.pm line 207." Any idea what can I do? Or what I did wrong? 
![perl mismatch](https://user-images.githubusercontent.com/45405439/155825430-21e280b9-1f43-4d37-a7ce-8da4c1e79f75.png)

**Comment by Lirt** [comment]
Hi @SuperSpital,

Which version of the plugin do you use? 

From the log you uploaded I would say you use GeoIP DB version 1. The last plugin version (2.0.0) is compatible only with GeoIP DB version 2. If you want to run with v1, please use tag 1.50 and follow [corresponding documentation](https://github.com/Vnet-as/postfwd-anti-geoip-spam-plugin/tree/v1.50.0).

**Comment by SuperSpital** [comment]
I use postfwd2 1.35, so following your plugin compatibility matrix, I installed plugin in version v1.21.

**Comment by SuperSpital** [comment]
May it be problem, that I use  libgeo-ip-perl in version 1.43-1 and perl in 5.18.2?

**Comment by Lirt** [comment]
Hi again,

The version of GeoIP perl module could be a problem. 

I can see that GeoIP has a dependency on DynaLoader but it doesn't say which version... I think the safest will be to try to update GeoIP perl module version. Your log says that `Geo::IP object version 1.43 does not match bootstrap parameter 1.45` -- so if I understand that correctly probably updating geo-ip perl module to 1.45 could be enough.

**Comment by SuperSpital** [comment]
Hi, thanks for very fast help.
That's weird, 1.43 is the newest available version. I tried apt-get update but it didn't help. Does it mean, that my Ubuntu 14.04.5 may be too old?

**Comment by Lirt** [comment]
Ubuntu 14 is already unsupported for some time. It's best to really upgrade the OS to also get security updates. Otherwise it could be possible to install various perl modules using CPAN/M, but still it is on your behalf to make it together and compatible :shrug:.

**Comment by SuperSpital** [comment]
It looks like I still have a lot of work to do, but I will try.
Thank you very much!
